# Generated by Django 4.2.7 on 2023-12-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_placas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='datetime',
            field=models.DateField(auto_now=True),
        ),
    ]
