# Generated by Django 4.2.7 on 2023-12-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_placas', '0003_rename_datetime_detections_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='ref_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
